config/routes.rb
Project::Application.routes.draw do

  resources :causes

  resources :donations

  resources :organizations

  resources :products
  root :to => 'products#index'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :amount, :product_id, :organization_id, :paid_out
  belongs_to :organization
  belongs_to :product
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<table class ="table table-striped">
<thead>
	<tr>
	<th></th>
	<th></th>
	</tr>
</thead>
<tbody>
	<tr>

	<td>Donation from <%= donation.organization.name %> for 
  <%= donation.amount %></td></tr></tbody></table>

app/views/donations/_form.html.erb
<%= simple_form_for(@donation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.collection_select(:organization_id, Organization.all, :id, :name, :prompt => "Select Donor") %>
    <br>
    <%= f.collection_select(:product_id, Product.all, :id, :name, :prompt => "Select Cause") %>
    <%= f.input :amount %> 
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation, :class => 'btn btn-mini' %> |
<%= link_to 'Back', donations_path, :class => 'btn btn-mini' %>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table class="table table-striped">
<thead>
  <tr>
    <th>Date Created</th>
    <th>Donor</th>
    <th>Cause</th>
    <th>Amount</th>
    <th>Paid Out</th>
    <th>Need Fulfilled</th>
    <th>Thank You Sent</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @donations.each do |donation| %>
  <tr>
    <td><%= donation.created_at %></td>
    <td><%= Organization.find(donation.organization_id).name %></td>
    <td><%= Product.find(donation.product_id).name %></td>
    <td><%= donation.amount %></td>
    <td><%= donation.paid_out %></td>
    <td><%= donation.fulfilled %></td>
    <td><%= donation.thankyou %></td>
    <td><%= link_to 'Show', donation, :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation), :class => 'btn btn-mini' %></td>
    <td>

		<%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>


    </td>
  </tr>
<%end%>
</tbody>
</table>

<br />

<%= link_to 'New Donation', new_donation_path, :class => 'btn btn-primary' %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path, :class => 'btn btn-mini' %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Donor:</b>
  <%= Organization.find(@donation.organization_id).name %>
</p>

<p>
  <b>Cause:</b>
  <%= Product.find(@donation.product_id).name %>
</p>

<p>
  <b>Amount:</b>
  <%= @donation.amount %>
</p>

<p>
  <b>Paid out:</b>
  <%= @donation.paid_out %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation), :class => 'btn btn-mini' %> |
<%= link_to 'Back', donations_path, :class => 'btn btn-mini' %>