config/routes.rb
Project::Application.routes.draw do

  resources :causes

  resources :donations

  resources :organizations

  resources :products
  root :to => 'products#index'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :agents
  attr_accessible :name
  has_many :donations
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table class="table table-striped">
<thead>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.name %></td>
    <td><%= link_to 'Show', organization, :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Remove', organization, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger'  %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Organization', new_organization_path, :class => 'btn btn-primary' %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><b>Name:</b></h2>
  <%= @organization.name %>
</p>

<% if @organization.donations.any? %>
<p>
  <h3>Donations:</h3>
  <ol class="donations">
    <% @organization.donations.each do |donation| %>
    <li> Donation for <%= donation.product.name %> of $<%= donation.amount %> </li>
    <% end %>
  </ol>
  <% end %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>